### ISSUE TITLE
Read me git clone

### ISSUE THREAD

**Issue by JAReith** [wenzeslaus/python-grass-addon#11]
Dear Vaclav,
`git clone git@github.com:wenzeslaus/python-grass-addon.git`  does not work, but instead `git clone https://github.com/wenzeslaus/python-grass-addon.git` should be used. Could you fix that in your READ ME?
Thanks
Best regards
Jonathan

**Comment by wenzeslaus** [comment]
The `git clone git@github.com` uses SSH, while `git clone https://github.com` version uses HTTPS. Both work for me (on Linux, Git 2.7.4). I can e.g. do `git clone git@github.com:JAReith/rasterUtils.git` from your account (*Clone or download* > *Use SSH*). There is not a big difference for cloning/pulling only, so I can use the HTTPS version in the example.
